version: '3.7'
services:
  db:
    image: postgres:12.6
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      # Authorize insecure connections;
      # used only in local development.
      POSTGRES_HOST_AUTH_METHOD: trust
      # Reference: <https://www.postgresql.org/docs/12/auth-trust.html>
    networks:
      - backend
  web:
    build: .
    init: true
    volumes:
      - .:/quickstart-webhooks
    environment:
      SQLALCHEMY_SECRET_KEY: super-secret-key
    depends_on:
      - db
    networks:
      - backend
  ngrok:
    image: shkoliar/ngrok:latest
    links:
      - web
    environment:
      DOMAIN: web
      PORT: 5000
      DEBUG: 'true'
      BIND_TLS: 'true'
    depends_on:
      - web
    networks:
      - backend

# Volumes for data persistence
volumes:
  data:
    driver: local

# Networks for container communication
networks:
  backend:
