"""empty message

Revision ID: 24616f8a2c99
Revises: 
Create Date: 2021-07-09 14:53:24.186457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24616f8a2c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
